-- ATTENZIONE: Questo script RESETTA completamente la tabella 'contatti'
-- Elimina la tabella esistente (e i suoi dati) e la ricrea pulita, senza trigger o vincoli che causano errori.

-- 1. Elimina la tabella corrotta e tutto ciò che dipende da essa (trigger, etc.)
DROP TABLE IF EXISTS public.contatti CASCADE;

-- 2. Ricrea la tabella in versione semplificata e funzionante
create table public.contatti (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  email text not null,
  messaggio text,
  attivita text
);

-- 3. Abilita la sicurezza
ALTER TABLE public.contatti ENABLE ROW LEVEL SECURITY;

-- 4. Ripristina i permessi
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON TABLE public.contatti TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- 5. Crea la policy per l'inserimento
CREATE POLICY "Permetti inserimento contatti a chiunque"
ON public.contatti
FOR INSERT
TO public
WITH CHECK (true);

-- 6. Ricarica la cache API
NOTIFY pgrst, 'reload config';
