-- Script SQL per configurare la tabella 'contatti' su Supabase
-- Esegui questo script nell'SQL Editor della tua dashboard Supabase

-- 1. Crea la tabella 'contatti'
create table if not exists public.contatti (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  email text not null,
  messaggio text,
  attivita text
);

-- 2. Abilita Row Level Security (RLS) per sicurezza
alter table public.contatti enable row level security;

-- 3. Crea una policy per permettere l'inserimento pubblico (anonimo)
-- Questo permette a chiunque visiti il sito di inviare il form
create policy "Permetti inserimento contatti a chiunque"
on public.contatti
for insert
to public
with check (true);

-- Nota: Non creando policy di SELECT, i dati inseriti NON saranno leggibili pubblicamente,
-- ma solo dalla dashboard di Supabase (o tramite service role). Questo protegge la privacy.
